[package]
name = "tmon"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Experimental lightweight terminal engine for Termy"

[lints]
workspace = true

[features]
benchmark-allocations = []

[dependencies]

[dev-dependencies]
alacritty_terminal = { workspace = true }
termy_core = { path = "../core" }
unicode-width = { workspace = true }
